version: '3.8'
services:
  postgres:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=survey-app
      - POSTGRES_PASSWORD=pass1234

  mongodb:
    image: mongo:5.0.4
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

volumes:
    data01:
      driver: local

networks:
    elastic:
      driver: bridge