spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: survey-app
    password: pass1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  elasticsearch:
    rest:
      username:
      password:
      read-timeout: 1m
      connection-timeout: 1s
      uris: localhost:9200

#  data:
#    mongodb:
#      authentication-database: admin
#      username: username
#      password: password
#      uri: mongodb://localhost:27017

server:
  port: 8080
